### ISSUE TITLE
dsym upload build script fails

### ISSUE THREAD

**Issue by respectTheCode** [rollbar/rollbar-ios#14] opened 2015-05-13 13:33 UTC
I had to use `BUILT_PRODUCTS_DIR` instead of `INSTALL_DIR`.

```python
info_file_path = os.path.join(os.environ['BUILT_PRODUCTS_DIR'], os.environ['INFOPLIST_PATH'])
```

**Comment by s0meone** [comment] 2015-07-07 08:49
Yes, same here. Thank you, your solution works.

I'm using Xcode 6.4.

**Comment by kshep** [comment] 2015-09-24 16:48
Duplicate of https://github.com/rollbar/rollbar-ios/issues/11

**Closed by kshep** 2015-09-24 16:48 UTC
