### ISSUE TITLE
Not able to get exact stace on the Rollbar error item page.

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/rollbar-ios#96] opened 2018-05-11 06:51 UTC
Hi,

I have integrated Rollbar-IOS Notifier successfully in my application but I cannot able to get exact error stack trace on the Rollbar console.
I have tried symbolication feature also by changing Strip Style to Debugging Symbols of my project build setting but still getting the same result.

Here is the screenshot of project build setting and Rollbar item page stack trace.

Build Setting :
![rollbar](https://user-images.githubusercontent.com/32199575/39910610-aa146438-5515-11e8-8e15-47d18d89133f.png)

Rollbar console stack trace:

![stacktrace](https://user-images.githubusercontent.com/32199575/39910587-96c4f4ec-5515-11e8-9417-2b893b65cf37.PNG)

Please let me know if I am doing anything wrong.

Wahid Ali

**Comment by rokob** [comment] 2018-05-21 16:43
Did you upload your DSYM?

**Comment by rokob** [comment] 2018-05-25 20:54
The issue is with the symbolication on the backend, it looks as if either a dsym is not uploaded or the code version associated with this error does not match the version associated with an uploaded dsym.

**Comment by jessewgibbs** [comment] 2018-08-07 23:41
I'm closing this since it's been open for quite a while.  Please reopen if this is still an issue.

**Closed by jessewgibbs** 2018-08-07 23:41 UTC
